# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [2]:
#todo: 
array = np.arange(10)
print(array)


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo:
array_ceros = np.zeros(5)
print("Array original:", array_ceros)
array_ceros[2] = 5
print("Array modificado:", array_ceros)

Array original: [0. 0. 0. 0. 0.]
Array modificado: [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [5]:
#todo: 
matriz_random = np.random.random((3, 3))
print("Matriz 3x3 de números aleatorios:")
print(matriz_random)

Matriz 3x3 de números aleatorios:
[[0.53191858 0.76610645 0.50025193]
 [0.9231274  0.88260396 0.5056004 ]
 [0.64619521 0.00194465 0.3067753 ]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [6]:
#todo:
arr = np.array([10, 20, 30, 40, 50])

arr_suma_5 = arr + 5
print("Array original:", arr)
print("Array después de sumar 5:", arr_suma_5)

numero_aleatorio = np.random.randint(1, 11)
arr_multiplicado = arr * numero_aleatorio

print("\nNúmero aleatorio generado:", numero_aleatorio)
print("Array después de multiplicar por el número aleatorio:", arr_multiplicado)

Array original: [10 20 30 40 50]
Array después de sumar 5: [15 25 35 45 55]

Número aleatorio generado: 3
Array después de multiplicar por el número aleatorio: [ 30  60  90 120 150]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [7]:
#todo:
matriz_identidad = np.identity(4)
print("Matriz identidad 4x4:")
print(matriz_identidad)

Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [10]:
#todo: 
numeros_pares = np.arange(0, 21, 2)
print("Array de números pares de 0 a 20:")
print(numeros_pares)

operador = np.full_like(numeros_pares, 2)

suma = numeros_pares + operador
print("Suma:")
print(suma)

resta = numeros_pares - operador
print("Resta:")
print(resta)

multiplicacion = numeros_pares * operador
print("Multiplicación:")
print(multiplicacion)

division = numeros_pares / operador
print("División:")
print(division)


Array de números pares de 0 a 20:
[ 0  2  4  6  8 10 12 14 16 18 20]
Suma:
[ 2  4  6  8 10 12 14 16 18 20 22]
Resta:
[-2  0  2  4  6  8 10 12 14 16 18]
Multiplicación:
[ 0  4  8 12 16 20 24 28 32 36 40]
División:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
